"""Create GitHub issues from diagnostic results."""

from __future__ import annotations

import subprocess
from typing import Optional

from .config import MaintainerConfig
from .diagnose import run_diagnostics, DiagnosticReport


def _build_issue_body(diagnostics: DiagnosticReport) -> str:
    """Build a Markdown issue body from diagnostic results."""
    lines = []
    lines.append("## Diagnostic Report (auto-generated by hermes-maintainer)\n")
    lines.append(f"**Errors:** {diagnostics.error_count}")
    lines.append(f"**Warnings:** {diagnostics.warn_count}\n")

    if diagnostics.items:
        lines.append("### Findings\n")
        lines.append("| Category | Severity | Title | Detail |")
        lines.append("|----------|----------|-------|--------|")
        for item in diagnostics.items:
            lines.append(f"| {item.category} | {item.severity} | {item.title} | {item.detail} |")
        lines.append("")

    lines.append("### Suggested Fixes\n")
    for item in diagnostics.items:
        if item.fix_hint:
            lines.append(f"- **{item.title}**: {item.fix_hint}")

    lines.append("\n---")
    lines.append("*Auto-generated by [hermes-maintainer](https://github.com/Jes614753-sketch/hermes-maintainer)*")

    return "\n".join(lines)


def create_issue_from_report(
    cfg: MaintainerConfig,
    title: Optional[str] = None,
    body: Optional[str] = None,
    labels: Optional[list[str]] = None,
    repo: str = "NousResearch/hermes-agent",
    dry_run: bool = False,
) -> dict:
    """Create a GitHub issue from diagnostic results.

    Returns a dict with keys: url, title, labels, body, error.
    """
    cfg.resolve_paths()

    # Run diagnostics if body not provided
    if body is None:
        diagnostics = run_diagnostics(cfg)
        body = _build_issue_body(diagnostics)
        if title is None:
            title = f"[hermes-maintainer] Auto-diagnosed: {diagnostics.error_count} errors, {diagnostics.warn_count} warnings"

    if title is None:
        title = "[hermes-maintainer] Issue report"

    if labels is None:
        labels = ["bug"]

    result = {
        "title": title,
        "labels": labels,
        "body": body,
    }

    if dry_run:
        return result

    # Create issue via gh CLI
    try:
        cmd = ["gh", "issue", "create", "--repo", repo, "--title", title, "--body", body]
        for label in labels:
            cmd.extend(["--label", label])

        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        if proc.returncode == 0:
            result["url"] = proc.stdout.strip()
        else:
            result["error"] = proc.stderr.strip()[:500]
    except FileNotFoundError:
        result["error"] = "gh CLI not found. Install from https://cli.github.com"
    except Exception as e:
        result["error"] = str(e)

    return result
